EE-22
einstein-devs/backend pull request #8
Opened 2023-04-25 23:10 UTC by fernando-bertolo

Rota de criação e listagem de eventos

2023-04-25 23:16 UTC, mateusgcoelho requested changes

2023-04-25 23:16 UTC, mateusgcoelho commented on src/modules/evento/event.controller.ts
> +        return this.eventService.createEvent(createEventDto);
Adicionar await antes do createEvent, pois é uma chamada assíncrona

2023-04-25 23:16 UTC, mateusgcoelho commented on src/modules/evento/event.service.ts
> +        return await this.prismaService.evento.findMany();
Adicionar tratamento de erro, try catch igual a rota acima de criação de evento

2023-04-25 23:16 UTC, mateusgcoelho commented on src/modules/evento/event.controller.ts
> +        return this.eventService.createEvent(createEventDto);
Ao invés de retornar direto a chamada do evento: 
```

return await this.eventService.createEvent(...);

```

Retornar a entidade padrão que ja esta criada:
```

const eventCreated = await this.createEvent(...);
return new DefaultResponse(eventCreated, "Evento criado com sucesso!");

```

2023-04-25 23:16 UTC, mateusgcoelho commented on src/modules/evento/event.controller.ts
> +        return await this.eventService.findMany();
ao invés de retornar direto a chamada do evento:
```

return await this.eventService.findMany();

```

Retornar a entidade padrão que ja esta criada:
```

const events = await this.eventService.findMany();
return new DefaultResponse(events, "");

```

2023-04-25 23:53 UTC, fernando-bertolo commented on src/modules/evento/event.controller.ts
> +        return this.eventService.createEvent(createEventDto);
Resolvido!

2023-04-25 23:53 UTC, fernando-bertolo commented on src/modules/evento/event.service.ts
> +        return await this.prismaService.evento.findMany();
Resolvido!

2023-04-25 23:53 UTC, fernando-bertolo commented on src/modules/evento/event.controller.ts
> +        return this.eventService.createEvent(createEventDto);
Resolvido!

2023-04-25 23:54 UTC, fernando-bertolo commented on src/modules/evento/event.controller.ts
> +        return await this.eventService.findMany();
Resolvido!

2023-04-26 21:44 UTC, mateusgcoelho requested changes

2023-04-26 21:44 UTC, mateusgcoelho commented on src/modules/evento/dto/create-evento-dto.ts
> +    dataHoraInicio: Date;
Adicionar decorator de checagem se o campo é uma data realmente, fazer isso tanto nesse quanto em datahoratermino

2023-04-28 14:10 UTC, mateusgcoelho requested changes

2023-04-28 14:10 UTC, mateusgcoelho commented on src/modules/evento/dto/create-evento-dto.ts
> +  codigo: string;
Adicionad @IsString()

2023-04-28 14:10 UTC, mateusgcoelho commented on src/modules/evento/dto/create-evento-dto.ts
> +  titulo: string;
Adicionad @IsString()

2023-04-28 14:10 UTC, mateusgcoelho commented on src/modules/evento/dto/create-evento-dto.ts
> +
Adicionad @IsString() e @IsOptional()

2023-04-28 14:10 UTC, mateusgcoelho commented on src/modules/evento/dto/update-evento-dto.ts
> +export class updateDTO {
Renomear de updateDTO para UpdateEventoDto

2023-04-28 14:10 UTC, mateusgcoelho commented on src/modules/evento/dto/params-post-eventos.ts
> +export class ParamsGetEvento {
Renomear de ParamsGetEvento para ParamsGetEventoDto

2023-04-28 14:10 UTC, mateusgcoelho commented on src/modules/evento/dto/create-evento-dto.ts
> +export class eventDTO {
Renomear de eventDTO para CreateEventoDto

2023-04-28 14:10 UTC, mateusgcoelho commented on src/modules/evento/event.controller.ts
> +export class EventController {
Renomear de EventController para EventoController

2023-04-28 14:10 UTC, mateusgcoelho commented on src/modules/evento/event.controller.ts
> +  constructor(private readonly eventService: EventService) {}
Renomear o EventService para EventoService

2023-04-28 14:10 UTC, mateusgcoelho commented on src/modules/evento/event.module.ts
> +export class EventModule {}
Renomear EventModule para EventoModule

2023-04-28 14:10 UTC, mateusgcoelho commented on src/modules/evento/event.service.ts
> +export class EventService {
Renomear EventService para EventoService

2023-04-28 14:20 UTC, fernando-bertolo commented on src/modules/evento/dto/create-evento-dto.ts
> +    dataHoraInicio: Date;
Resolvido!

2023-04-28 21:36 UTC, mateusgcoelho requested changes

2023-04-28 21:36 UTC, mateusgcoelho commented on src/modules/evento/dto/update-evento-dto.ts
> +export class updateEventoDTO {
Sempre em classes, utiliza letra maiúscula na primeira

2023-04-28 22:50 UTC, fernando-bertolo commented on src/modules/evento/dto/create-evento-dto.ts
> +  codigo: string;
Resolvido!

2023-04-28 22:50 UTC, fernando-bertolo commented on src/modules/evento/dto/create-evento-dto.ts
> +  titulo: string;
Resolvido!

2023-04-28 22:50 UTC, fernando-bertolo commented on src/modules/evento/dto/create-evento-dto.ts
> +
Resolvido!

2023-04-28 22:50 UTC, fernando-bertolo commented on src/modules/evento/dto/update-evento-dto.ts
> +export class updateDTO {
Resolvido!

2023-04-28 22:51 UTC, fernando-bertolo commented on src/modules/evento/dto/update-evento-dto.ts
> +export class updateDTO {
Resolvido!

2023-04-28 22:51 UTC, fernando-bertolo commented on src/modules/evento/dto/params-post-eventos.ts
> +export class ParamsGetEvento {
Resolvido!

2023-04-28 22:51 UTC, fernando-bertolo commented on src/app.module.ts
> +    EventModule,
Resolvido!

2023-04-28 22:51 UTC, fernando-bertolo commented on src/modules/evento/event.controller.ts
> +export class EventController {
Resolvido!

2023-04-28 22:51 UTC, fernando-bertolo commented on src/modules/evento/event.controller.ts
> +  constructor(private readonly eventService: EventService) {}
Resolvido!****

2023-04-28 22:52 UTC, fernando-bertolo commented on src/modules/evento/event.module.ts
> +export class EventModule {}
Resolvido!

2023-04-28 22:52 UTC, fernando-bertolo commented on src/modules/evento/event.service.ts
> +export class EventService {
Resolvido!

2023-04-28 22:52 UTC, fernando-bertolo commented on src/modules/evento/dto/update-evento-dto.ts
> +export class updateEventoDTO {
Resolvido!

2023-05-01 18:25 UTC, merged